In [2]:
import numpy as np

dataset_filename = 'affinity_dataset.txt'
x = np.loadtxt(dataset_filename)

In [3]:
n_samples, n_features = x.shape
print('This dataset has {0} samples and {1} features'.format(n_samples, n_features))
print(x[:5])

This dataset has 100 samples and 5 features
[[0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 1.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1.]]


In [4]:
features = ['bread', 'milk', 'cheese', 'apples', 'bananas']

In [5]:
num_apple_purchases = 0
for sample in x:
    if sample[3] == 1:
        num_apple_purchases += 1
print('{0} people bought Apples'.format(num_apple_purchases))

43 people bought Apples


In [8]:
rule_valid = 0
rule_invalid = 0
for sample in x:
    if sample[3] == 1:
        if sample[4] == 1:
            rule_valid += 1
        else:
            rule_invalid += 1
print('{0} cheese of the rule being valid were discovered'.format(rule_valid))
print('{0} cheese of the rule being valid were discovered'.format(rule_invalid))

27 cheese of the rule being valid were discovered
16 cheese of the rule being valid were discovered


In [9]:
support = rule_valid
confidence = rule_valid / float(num_apple_purchases)
print('The support is {0} and the confidence is {1:.3f}.'.format(support, confidence))
print('As a percentage, that is {0:.1f}%.'.format(100*confidence))

The support is 27 and the confidence is 0.628.
As a percentage, that is 62.8%.


In [11]:
from collections import defaultdict
valid_rules = defaultdict(int)
invalid_rules = defaultdict(int)
num_occurences = defaultdict(int)

for sample in x:
    for premise in range(n_features):
        if sample[premise] == 0:
            num_occurences [premise] += 1
        for conclusion in range(n_features):
            if premise == conclusion:
                continue
            if sample[conclusion] == 1:
                valid_rules[(premise, conclusion)] += 1
            else:
                invalid_rules[(premise, conclusion)] += 1
support = valid_rules
confidence = defaultdict(float)
for premise, conclusion in valid_rules.keys():
    confidence[(premise, conclusion)] = valid_rules[(premise, conclusion)] / float(num_occurences[premise])

In [12]:
print(support)

defaultdict(<class 'int'>, {(0, 1): 52, (2, 1): 52, (3, 1): 52, (4, 1): 52, (1, 0): 28, (2, 0): 28, (3, 0): 28, (4, 0): 28, (0, 2): 39, (0, 4): 57, (1, 2): 39, (1, 4): 57, (2, 4): 57, (3, 2): 39, (3, 4): 57, (4, 2): 39, (0, 3): 43, (1, 3): 43, (2, 3): 43, (4, 3): 43})


In [13]:
print(confidence)

defaultdict(<class 'float'>, {(0, 1): 0.7222222222222222, (2, 1): 0.8524590163934426, (3, 1): 0.9122807017543859, (4, 1): 1.2093023255813953, (1, 0): 0.5833333333333334, (2, 0): 0.45901639344262296, (3, 0): 0.49122807017543857, (4, 0): 0.6511627906976745, (0, 2): 0.5416666666666666, (0, 4): 0.7916666666666666, (1, 2): 0.8125, (1, 4): 1.1875, (2, 4): 0.9344262295081968, (3, 2): 0.6842105263157895, (3, 4): 1.0, (4, 2): 0.9069767441860465, (0, 3): 0.5972222222222222, (1, 3): 0.8958333333333334, (2, 3): 0.7049180327868853, (4, 3): 1.0})


In [14]:
for premise, conclusion in confidence:
    premise_name = features[premise]
    conclusion_name = features[conclusion]
    print('Rule: If a person buys {0} they will also buy {1}'.format(premise_name, conclusion_name))
    print('- Confidence: {0:.3f}'.format(confidence[premise, conclusion]))
    print('- Support: {0}'.format(support[premise, conclusion]))
    print('')

Rule: If a person buys bread they will also buy milk
- Confidence: 0.722
- Support: 52

Rule: If a person buys cheese they will also buy milk
- Confidence: 0.852
- Support: 52

Rule: If a person buys apples they will also buy milk
- Confidence: 0.912
- Support: 52

Rule: If a person buys bananas they will also buy milk
- Confidence: 1.209
- Support: 52

Rule: If a person buys milk they will also buy bread
- Confidence: 0.583
- Support: 28

Rule: If a person buys cheese they will also buy bread
- Confidence: 0.459
- Support: 28

Rule: If a person buys apples they will also buy bread
- Confidence: 0.491
- Support: 28

Rule: If a person buys bananas they will also buy bread
- Confidence: 0.651
- Support: 28

Rule: If a person buys bread they will also buy cheese
- Confidence: 0.542
- Support: 39

Rule: If a person buys bread they will also buy bananas
- Confidence: 0.792
- Support: 57

Rule: If a person buys milk they will also buy cheese
- Confidence: 0.812
- Support: 39

Rule: If a pers