In [2]:
# 외부 패키지인 numpy 불러옴 (np라는 이름으로 불러옴)
import numpy as np

In [3]:
# 패턴을 찾기 위한 대상 데이터 로딩 (numpy의 loadtxt 함수 호출)
dataset_filename = "affinity_dataset.txt"
x = np.loadtxt(dataset_filename)
n_samples, n_features = x.shape
print('This dataset has {0} samples and {1} features'.format(n_samples, n_features))
print(x[:5])

This dataset has 100 samples and 5 features
[[0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 1.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1.]]


In [7]:
# 속성의 이름을 정해줌 (txt 데이터에는 속성 이름이 없으므로 임의로 정해줌)
features = ["bread", "milk", "cheese", "apples", "bananas"]

In [13]:
# 7개의 행까지 프린트, 각각의 행은 샘플 하나에 해당함
# X는 길이가 100인 배열이며, 배열의 각 요소는 다시 길이가 5인 배열
# 콜론(:)의 의미는 처음부터 콜론 뒤에 있는 숫자까지라는 뜻
# 따라서 X[:7]는 배열의 첫번째 요소부터 7번째 요소까지를 의미
# index로는 0에서부터 6까지 포함
# 이 배열의 각 요소는 길이가 5인 배열이므로 아래와 같이 프린팅 됨

print(x[:7])

[[0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 1.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1.]]


In [9]:
# 7개의 행과 3개의 열(속성)을 프린트
# 행과 열의 범위를 주어 접근
# 행은 콤마(,) 앞에 위치하고 열은 뒤에 위치

print(x[:7, :3])

[[0. 1. 0.]
 [1. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# 하나의 샘플만 프린트할 경우 - 두번째 사람이 구매 이력
print(x[1])

[1. 1. 0. 0. 0.]


In [15]:
# 하나의 샘플의 특정 상품 구매여부만 프린트할 경우
# 세번째 사람이 네번째 상품인 사과 구매 여부
print(x[2][3])

0.0


In [17]:
# 각각의 행을 읽으면서 그 행을 프린트하고
# 바로 옆에 그 사람의 사과 구매 여부를 프린트
# for 문을 돌리면서 X에 있는 요소가 순서대로 sample에 카피됨
for sample in x:
    print('{0} {1}'.format(sample, sample[3]))

[0. 1. 0. 0. 0.] 0.0
[1. 1. 0. 0. 0.] 0.0
[0. 0. 1. 0. 1.] 0.0
[1. 1. 0. 0. 0.] 0.0
[0. 0. 1. 1. 1.] 1.0
[0. 1. 0. 0. 0.] 0.0
[0. 0. 1. 1. 1.] 1.0
[0. 0. 1. 1. 0.] 1.0
[0. 1. 0. 1. 0.] 1.0
[0. 1. 0. 0. 1.] 0.0
[0. 0. 0. 1. 0.] 1.0
[1. 0. 1. 0. 0.] 0.0
[1. 0. 0. 0. 1.] 0.0
[0. 1. 1. 0. 0.] 0.0
[0. 0. 1. 0. 1.] 0.0
[0. 1. 0. 1. 0.] 1.0
[1. 1. 0. 1. 1.] 1.0
[0. 0. 0. 1. 1.] 1.0
[0. 1. 0. 0. 1.] 0.0
[1. 1. 0. 1. 0.] 1.0
[0. 1. 1. 0. 0.] 0.0
[0. 1. 0. 0. 1.] 0.0
[0. 0. 1. 0. 0.] 0.0
[1. 0. 0. 0. 1.] 0.0
[0. 1. 0. 1. 0.] 1.0
[1. 0. 0. 1. 1.] 1.0
[0. 1. 1. 0. 0.] 0.0
[0. 1. 0. 0. 1.] 0.0
[0. 0. 0. 0. 1.] 0.0
[1. 0. 0. 0. 1.] 0.0
[0. 1. 0. 1. 1.] 1.0
[1. 0. 0. 0. 0.] 0.0
[0. 1. 0. 0. 0.] 0.0
[1. 0. 0. 0. 0.] 0.0
[0. 0. 1. 1. 1.] 1.0
[0. 0. 1. 1. 1.] 1.0
[0. 0. 1. 1. 1.] 1.0
[1. 0. 0. 1. 0.] 1.0
[0. 1. 0. 0. 1.] 0.0
[1. 1. 0. 0. 0.] 0.0
[0. 0. 0. 0. 1.] 0.0
[0. 1. 0. 1. 1.] 1.0
[0. 1. 0. 1. 0.] 1.0
[0. 1. 0. 0. 1.] 0.0
[1. 1. 1. 1. 0.] 1.0
[1. 0. 0. 0. 1.] 0.0
[0. 0. 0. 1. 1.] 1.0
[1. 1. 0. 0. 

In [19]:
# 사과를 구입한 사람의 수를 카운팅
# for문을 돌리며 X에 있는 요소들을 하나씩 sample에 복사하여 체크

APPLE_INDEX = 3
num_apple_purchases = 0
for sample in x:# 중요2
    if sample[APPLE_INDEX] == 1:
        num_apple_purchases += 1
print("{0} people bought Apples".format(num_apple_purchases))

43 people bought Apples


In [21]:
# 사과를 산 사람이 바나나도 산 경우가 얼마나 많은가?
# 규칙이 유효한 경우와 그렇지 않은 경우 모두 기록
# 유효한 경우는 사과를 산 사람 중에서 바나나도 산 사람의 수 (교집합)
# 비유효한 경우는 사과를 산 사람 중에서 바나나는 사지 않은 사람의 수 (차집합)
rule_valid = 0
rule_invalid = 0
for sample in x:
    if sample[3] == 1: # This person bought Apples
        if sample[4] == 1: # This person bought Apples and Bananas
            rule_valid += 1
        else: # This person bought Apples, but not Bananas
            rule_invalid += 1
print("{0} cases of the rule being valid were discovered".format(rule_valid))
print("{0} cases of the rule being invalid were discovered".format(rule_invalid))

27 cases of the rule being valid were discovered
16 cases of the rule being invalid were discovered


In [28]:
# 지지도(Support)와 신뢰도(Confidence)를 계산하기 위한 정보가 모두 존재하므로 계산
# 사과를 사면(전제) -> 바나나를 산다(결론)
support = rule_valid  # 이 규칙이 발견된 횟수
confidence = rule_valid / float(num_apple_purchases) # (이 규칙이 발견된 횟수)/(전제에 해당하는 샘플의 개수)

# 프린트 시에 숫자 포맷을 지정하여 프린트할 수 있음
print("The support is {0} and the confidence is {1:.3f}.".format(support, confidence))
print("The support is {0} and the confidence is {1}.".format(support, confidence))
print('As a percentage, that is {0:.1f}%.'.format(100*confidence))

The support is 27 and the confidence is 0.628.
The support is 27 and the confidence is 0.627906976744186.
As a percentage, that is 62.8%.


In [24]:
# 이제 해야할 것은 모든 규칙을 만들어보고 그 규칙이 맞는 경우와 틀리는 경우 계산
# (전제,결론) 쌍이므로 순서가 있는 상품의 쌍
# 이를 위해 자료형은 딕셔너리 구조 사용 (참고자료: 소프트웨어공학_5주.pdf, p.28부터)
# 기본 딕셔너리를 사용하지 않고 defaultdict를 사용
# 파이썬 표준 라이브러리은 collections 패키지로부터 import

from collections import defaultdict
# Now compute for all possible rules
valid_rules = defaultdict(int)   # value 가 int 값을 갖는 딕셔너리 선언, 각 규칙이 참인 샘플 개수를 저장
invalid_rules = defaultdict(int) # value 가 int 값을 갖는 딕셔너리 선언, 각 규칙이 거짓인 샘플 개수를 저장
num_occurences = defaultdict(int) # value 가 int 값을 갖는 딕셔너리 선언, 각 규칙의 전제가 발견되는 샘플 개수를 저장

In [25]:
# 아무 데이터도 넣지 않은 defaultdict를 프린트해본다.
# 
print(defaultdict(int))

defaultdict(<class 'int'>, {})


In [ ]:
#앞으로 valid_rules에는 다음과 같은 자료가 저장될 것임 (데이터를 읽으면서)
# {(0, 1): 13, (1, 2): 11} <----- 첫번째 요소: 상품0을 구매했을 때 상품1을 구매한 경우의 샘플 개수는 13개
#                                 두번째 요소: 상품1을 상품을 구매했을 때 상품2를 구매한 경우의 샘플 개수는 11개    
# 위의 딕셔너리에 모든 상품 쌍(순서있음)에 대한 요소들이 추가될 것임

In [31]:
for sample in x:
    for premise in range(len(features)):
        if sample[premise] == 0: continue
        # Record that the premise was bought in another transaction
        num_occurences [premise] += 1
        for conclusion in range(len(features)):
            if premise == conclusion:  # It makes little sense to measure if X -> X.
                continue
            if sample[conclusion] == 1:
                # This person also bought the conclusion item
                valid_rules[(premise, conclusion)] += 1
            else:
                # This person bought the premise, but not the conclusion
                invalid_rules[(premise, conclusion)] += 1
support = valid_rules
confidence = defaultdict(float)
for premise, conclusion in valid_rules.keys():
    confidence[(premise, conclusion)] = valid_rules[(premise, conclusion)] / float(num_occurences[premise])

In [44]:
for a, b in valid_rules.keys(): # equals to "for a, b in valid_rules:"
    print(a, b)

print(valid_rules.keys())

0 1
2 1
3 1
4 1
1 0
2 0
3 0
4 0
0 2
0 4
1 2
1 4
2 4
3 2
3 4
4 2
0 3
1 3
2 3
4 3
dict_keys([(0, 1), (2, 1), (3, 1), (4, 1), (1, 0), (2, 0), (3, 0), (4, 0), (0, 2), (0, 4), (1, 2), (1, 4), (2, 4), (3, 2), (3, 4), (4, 2), (0, 3), (1, 3), (2, 3), (4, 3)])


In [27]:
print(support)

defaultdict(<class 'int'>, {(0, 1): 52, (2, 1): 52, (3, 1): 52, (4, 1): 52, (1, 0): 28, (2, 0): 28, (3, 0): 28, (4, 0): 28, (0, 2): 39, (0, 4): 57, (1, 2): 39, (1, 4): 57, (2, 4): 57, (3, 2): 39, (3, 4): 57, (4, 2): 39, (0, 3): 43, (1, 3): 43, (2, 3): 43, (4, 3): 43})


In [26]:
print(confidence)

defaultdict(<class 'float'>, {(0, 1): 0.7222222222222222, (2, 1): 0.8524590163934426, (3, 1): 0.9122807017543859, (4, 1): 1.2093023255813953, (1, 0): 0.5833333333333334, (2, 0): 0.45901639344262296, (3, 0): 0.49122807017543857, (4, 0): 0.6511627906976745, (0, 2): 0.5416666666666666, (0, 4): 0.7916666666666666, (1, 2): 0.8125, (1, 4): 1.1875, (2, 4): 0.9344262295081968, (3, 2): 0.6842105263157895, (3, 4): 1.0, (4, 2): 0.9069767441860465, (0, 3): 0.5972222222222222, (1, 3): 0.8958333333333334, (2, 3): 0.7049180327868853, (4, 3): 1.0})


In [32]:
# 규칙 출력
for premise, conclusion in confidence:
    premise_name = features[premise]
    conclusion_name = features[conclusion]
    print('Rule: If a person buys {0} they will also buy {1}'.format(premise_name, conclusion_name))
    print('- Confidence: {0:.3f}'.format(confidence[premise, conclusion]))
    print('- Support: {0}'.format(support[premise, conclusion]))
    print('')

Rule: If a person buys bread they will also buy milk
- Confidence: 0.583
- Support: 91

Rule: If a person buys cheese they will also buy milk
- Confidence: 0.478
- Support: 85

Rule: If a person buys apples they will also buy milk
- Confidence: 0.570
- Support: 106

Rule: If a person buys bananas they will also buy milk
- Confidence: 0.621
- Support: 133

Rule: If a person buys milk they will also buy bread
- Confidence: 0.328
- Support: 67

Rule: If a person buys cheese they will also buy bread
- Confidence: 0.242
- Support: 43

Rule: If a person buys apples they will also buy bread
- Confidence: 0.296
- Support: 55

Rule: If a person buys bananas they will also buy bread
- Confidence: 0.355
- Support: 76

Rule: If a person buys bread they will also buy cheese
- Confidence: 0.346
- Support: 54

Rule: If a person buys bread they will also buy bananas
- Confidence: 0.673
- Support: 105

Rule: If a person buys milk they will also buy cheese
- Confidence: 0.353
- Support: 72

Rule: If a p

In [35]:
# 특정 조건에 대해 출력하는 함수
def print_rule(premise, conclusion, support, confidence, features):
    premise_name = features[premise]
    conclusion_name = features[conclusion]
    print('Rule: If a person buys {0} they will also buy {1}'.format(premise_name, conclusion_name))
    print('- Confidence: {0:.3f}'.format(confidence[premise, conclusion]))
    print('- Support: {0}'.format(support[premise, conclusion]))
    print('')

In [36]:
premise = 1
conclusion = 3
print_rule(premise, conclusion, support, confidence, features)

Rule: If a person buys milk they will also buy apples
- Confidence: 0.475
- Support: 97



In [37]:
# Sort by support (규칙 id 값으로)
from pprint import pprint
pprint(list(support.items()))

[((0, 1), 91),
 ((2, 1), 85),
 ((3, 1), 106),
 ((4, 1), 133),
 ((1, 0), 67),
 ((2, 0), 43),
 ((3, 0), 55),
 ((4, 0), 76),
 ((0, 2), 54),
 ((0, 4), 105),
 ((1, 2), 72),
 ((1, 4), 138),
 ((2, 4), 117),
 ((3, 2), 105),
 ((3, 4), 138),
 ((4, 2), 99),
 ((0, 3), 70),
 ((1, 3), 97),
 ((2, 3), 109),
 ((4, 3), 124)]


In [48]:
# Sort by support
from operator import itemgetter
sorted_support = sorted(support.items(), key=itemgetter(1), reverse=True)
for index in range(5):
    print("Rule #{0}".format(index + 1))
    (premise, conclusion) = sorted_support[index][0]
    print_rule(premise, conclusion, support, confidence, features)

Rule #1
Rule: If a person buys milk they will also buy bananas
- Confidence: 0.676
- Support: 138

Rule #2
Rule: If a person buys apples they will also buy bananas
- Confidence: 0.742
- Support: 138

Rule #3
Rule: If a person buys bananas they will also buy milk
- Confidence: 0.621
- Support: 133

Rule #4
Rule: If a person buys bananas they will also buy apples
- Confidence: 0.579
- Support: 124

Rule #5
Rule: If a person buys cheese they will also buy bananas
- Confidence: 0.657
- Support: 117



In [49]:
# Sort by confidence
sorted_confidence = sorted(support.items(), key=itemgetter(1), reverse=True)
for index in range(5):
    print("Rule #{0}".format(index + 1))
    (premise, conclusion) = sorted_confidence[index][0]
    print_rule(premise, conclusion, support, confidence, features)

Rule #1
Rule: If a person buys milk they will also buy bananas
- Confidence: 0.676
- Support: 138

Rule #2
Rule: If a person buys apples they will also buy bananas
- Confidence: 0.742
- Support: 138

Rule #3
Rule: If a person buys bananas they will also buy milk
- Confidence: 0.621
- Support: 133

Rule #4
Rule: If a person buys bananas they will also buy apples
- Confidence: 0.579
- Support: 124

Rule #5
Rule: If a person buys cheese they will also buy bananas
- Confidence: 0.657
- Support: 117

